### ISSUE TITLE
문제

### ISSUE THREAD

**Issue by koipkoi** [koipkoi/pokeruby-kr#11]
- [x] 메시지 상자 텍스트 위치 변경 필요
![298829919-9af6c91a-ba2d-40e2-9b29-29c907d01058](https://github.com/koipkoi/pokeruby-kr/assets/39587773/76f80eee-ac60-45f3-bd66-131ed0131f21)

**Comment by poketony** [comment]
- [ ] 특정 상황에서 '까' 폰트가 깨지는 문제 발생
![pokesapphire-2](https://github.com/koipkoi/pokeruby-kr/assets/57011422/0b96f943-62db-4b4f-a499-7fcb0d75274b)

**Comment by poketony** [comment]
- [ ] 스타팅 포켓몬 선택 화면 조정
![pokesapphire-3](https://github.com/koipkoi/pokeruby-kr/assets/57011422/6958b4a4-947a-493c-a828-d60415aa1181)![pokeemerald-2](https://github.com/koipkoi/pokeruby-kr/assets/57011422/e80404ed-5d89-401a-92e0-e0c44796159f)
<RS/E>

**Comment by poketony** [comment]
- [ ] 배틀타워 참가 불가 포켓몬 코드 확인 및 조정
	.string "3마리 준비해 주십시오\p"
	.string "또한 지니게 할 도구도\n"
	.string "모두 다른 도구로 해주세요!\p"
	.string "그리고 알{STR_VAR_1}"
	.string "참가시킬 수 없습니다!\p"
	.string "준비되면\n"
	.string "다시 방문해 주십시오$"
