### ISSUE TITLE
오리지널 컬러로 맞추기

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeruby-kr#4]
- [x] 상태화면 폰트

![1  POKEMON_RUBY_AXVJ00-1](https://github.com/poketony/pokeruby-kr/assets/57011422/b445a5fe-e378-46aa-b572-e15b68c2612b)![pokeruby-0](https://github.com/poketony/pokeruby-kr/assets/57011422/49303577-b90b-47b5-97a8-44f0afaf95ae)

우측 상단의 '그만둔다' 부분과, 일판 원본에 비해 검은 폰트가 조금 진한 감이 있네요. 수정 가능하시면 부탁드리겠습니다!

**Comment by koipkoi** [comment]
PC 메뉴 텍스트 (마킹 메뉴의 팔레트는 그대로 둬야함)
![pokeruby_modern_01](https://github.com/poketony/pokeruby-kr/assets/39587773/45a2045d-a45c-4dde-ba27-ae730f3fd795)![pokeruby_jp_01](https://github.com/poketony/pokeruby-kr/assets/39587773/b4945fc3-89b3-4aca-928e-0ac217e73994)
