### ISSUE TITLE
메일 발신자명/조사 순서 바꾸기

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeruby-kr#43]
![000400000765B300 gbavc-0](https://github.com/koipkoi/pokeruby-kr/assets/57011422/af2f6d3b-6f67-4ff0-bc51-b9f0818c4914)

수정 전 에메랄드와 마찬가지로 이런 현상이 나타나네요! 
이쪽도 똑같이 작업해 주시면 될 것 같습니다

**Comment by poketony** [comment]
![000400000765B300 gbavc-0](https://github.com/koipkoi/pokeruby-kr/assets/57011422/e7fe6825-e9ac-4d45-8144-d7f0b2a93896)

순서는 바뀌었는데 이름과 조사 사이에 공백이 한 칸 들어가게 바뀌었네요! 이 공백만 지워 주시면 될 것 같습니다:)

**Comment by koipkoi** [comment]
이름 바이트수에 따라 여백을 채우는게 확인되었습니다.

총 6바이트 중에 이름을 제외한 부분이 공백으로 채워지고 있습니다.
한글 기준 2자는 4바이트 이므로 여백 2글자가 채워집니다.

해당 문제를 해결할수는 있지만 기존 세이브에서는 띄어쓰기가 그대로 남을것으로 보입니다.

그리고 에메랄드에서도 적용이 되어야할 것같네요.
