### ISSUE TITLE
텍스트 위치 변경 필요

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeruby-kr#7]
![pokeruby-0](https://github.com/poketony/pokeruby-kr/assets/57011422/f05ed43f-c8c2-4945-ad74-cb9f9d48a4de)

다른 것들도 발견할 경우 차례로 올리겠습니다!

**Comment by koipkoi** [comment]
![295582617-838656c1-4afb-4297-9a24-301ad2833804](https://github.com/poketony/pokeruby-kr/assets/39587773/7efec517-94ce-44b9-941a-bc1c2c58d895)

**Comment by koipkoi** [comment]
@poketony 제가 텍스트 위치 변경이라고 바꾸긴했지만 위처럼 공간이 부족하여 깨지는 경우도 올려주셔도 됩니다.

**Comment by koipkoi** [comment]
![pokeruby_modern_01](https://github.com/poketony/pokeruby-kr/assets/39587773/1baddc15-6950-46dd-bafd-7aa7d69c3b3e)

**Comment by koipkoi** [comment]
가방 나무열매, 기술머신 개수 표시 점검 필요

![pokeruby_modern_01](https://github.com/poketony/pokeruby-kr/assets/39587773/eb3d68c8-10f9-4c4c-93d5-c446fc256e8c)

**Comment by koipkoi** [comment]
이상한사탕 사용 후 정보창 내용이 깨지는 증상

![pokeruby_modern_01](https://github.com/poketony/pokeruby-kr/assets/39587773/931bd86e-94a2-4a77-92e1-dba9ef5a02a9)

**Comment by koipkoi** [comment]
배틀 기술 목록창 조절

![pokeruby_modern_01](https://github.com/poketony/pokeruby-kr/assets/39587773/9ff5e69c-13bd-4ead-aaed-165cec6a1a81)![pokeruby_jp_01](https://github.com/poketony/pokeruby-kr/assets/39587773/d5168265-5981-4d23-ab18-d310f4c967b6)

**Comment by koipkoi** [comment]
스크립트 상으로 뜨는 선택 메뉴들 모두 1타일 밀려나옴

1
![pokeruby_modern_01](https://github.com/poketony/pokeruby-kr/assets/39587773/8273eb1c-5ebd-4e0f-bae2-7e5bc71deaf4)

2
![295580123-f05ed43f-c8c2-4945-ad74-cb9f9d48a4de](https://github.com/poketony/pokeruby-kr/assets/39587773/af57b539-b1e6-4e7b-b8ab-b90786107f6c)

**Comment by poketony** [comment]
![pokeruby-0](https://github.com/koipkoi/pokeruby-kr/assets/57011422/9af6c91a-ba2d-40e2-9b29-29c907d01058)
게임코너 메시지 창도 부탁드립니다!

**Comment by koipkoi** [comment]
@poketony 새로운 이슈에 남겨주실 수 있을까요? 이쪽에 남긴건 따로 체크해둔게 없어서 혼동할 수 있어서 '- [ ] 내용' 형식으로 남겨주시면 됩니다.
